// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8VFMEGbkgnPEzI6JCGuYIPr1dGmiPMs0',
    appId: '1:545786364087:web:1812ffc47a91542cbbcd32',
    messagingSenderId: '545786364087',
    projectId: 'plant-friends-app',
    authDomain: 'plant-friends-app.firebaseapp.com',
    storageBucket: 'plant-friends-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx_EwH-Dc0oXBcaxPqtKncLtyf-WqWYx0',
    appId: '1:545786364087:android:6c52e373666adc59bbcd32',
    messagingSenderId: '545786364087',
    projectId: 'plant-friends-app',
    storageBucket: 'plant-friends-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtWGAPjE0cvINWp5lLB28oLU3rDJfW58',
    appId: '1:545786364087:ios:19aba50c9e659936bbcd32',
    messagingSenderId: '545786364087',
    projectId: 'plant-friends-app',
    storageBucket: 'plant-friends-app.appspot.com',
    iosBundleId: 'com.hwr.plantFriends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQtWGAPjE0cvINWp5lLB28oLU3rDJfW58',
    appId: '1:545786364087:ios:19aba50c9e659936bbcd32',
    messagingSenderId: '545786364087',
    projectId: 'plant-friends-app',
    storageBucket: 'plant-friends-app.appspot.com',
    iosBundleId: 'com.hwr.plantFriends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8VFMEGbkgnPEzI6JCGuYIPr1dGmiPMs0',
    appId: '1:545786364087:web:1812ffc47a91542cbbcd32',
    messagingSenderId: '545786364087',
    projectId: 'plant-friends-app',
    authDomain: 'plant-friends-app.firebaseapp.com',
    storageBucket: 'plant-friends-app.appspot.com',
  );
}
