import 'package:flutter_local_notifications/flutter_local_notifications.dart'
class NotificationService{
final FlutterLocalNotificationsPlugin notificationsPlugin = FlutterLocalNotificationsPlugin();
}